version: '3.8'

services:
  db:
    image: postgres:15
    container_name: yam_master_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: casino_password
      POSTGRES_DB: yam_master
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: yam_master_server
    restart: always
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: postgresql://admin:casino_password@db:5432/yam_master
      PORT: 3005 
    depends_on:
      - db

volumes:
  postgres_data: